### ISSUE TITLE
ObservableMap only show Empty Object on Mobx Devtools

### ISSUE THREAD

**Issue by fortezhuo** [mobxjs/mobx-devtools#27]
Hi,

Thanks for great Chrome Extension.

I used to use this extension to trace mobx store data. Everything seems ok. But I can't trace value of Observable Map

![ss](https://user-images.githubusercontent.com/9128724/37859472-cfd5ac08-2f46-11e8-89e2-098f7bc5d873.jpeg)

For temp solution, I have to set toJS() function to global window like this : 
![ss2](https://user-images.githubusercontent.com/9128724/37859529-769fc564-2f47-11e8-8ef4-6ebaab3fd9fe.jpeg)

So can you enhance this great extension to display value of  observable Map ?

**Comment by andykog** [comment]
Fixed in 0.9.15

**Comment by fortezhuo** [comment]
Hi Andy,

Thanks for quick response.
I have upgraded to 0.9.15. But now this extension had been broken. This extension only show blank and no inspectable information shown up.

![ss1](https://user-images.githubusercontent.com/9128724/37870356-5687b9f0-2ffe-11e8-9a3c-aff42a9d2a4c.jpeg)

![ss2](https://user-images.githubusercontent.com/9128724/37870346-0a98f8d8-2ffe-11e8-8b7a-028bc62bbc22.jpeg)


And here is my information : 
- macOS High Sierra 13.3
- Opera 51.x upgraded to 52.x (Chrome 65)
- Mobx 4.0.2
- Mobx React 5.0.0
- React 16.2

**Comment by andykog** [comment]
@hedikasmanto, sorry, webpack build failed because of eslint error but the process exited with code 0 due to misconfiguration. Fixed in 0.9.16

**Comment by fortezhuo** [comment]
Thanks Andy. I have upgraded to latest and it almost works perfect. Some issues that I found, if my data have Date or Arrays datatype, those datatypes won't be inspectable and still be Empty Object.
Mobx Extension :
![ss](https://user-images.githubusercontent.com/9128724/37880667-577622e4-30b6-11e8-8638-7913788532e7.jpeg)

My Global toJS function
![ss1](https://user-images.githubusercontent.com/9128724/37880719-decc8f58-30b6-11e8-92ab-d11142f2332f.jpeg)

**Comment by andykog** [comment]
@hedikasmanto, dates should now be displayed fine (v0.9.17).
Are you sure that those values are actually arrays? For me both native and observable arrays are shown fine:
<img width="208" alt="screen shot 2018-03-28 at 21 18 48" src="https://user-images.githubusercontent.com/6760207/38048304-a317eb60-32cd-11e8-9480-cfe68271cf86.png">
Could you try `right click on the value → store as global variable` and make sure that you have an array there?

**Comment by fortezhuo** [comment]
I have upgraded this extension (0.19.7) And problem still occurs. And FYI, I have store named "flow", and flowStore has observableMap named "data". And In that observableMap "data" contains value date and array

![ss](https://user-images.githubusercontent.com/9128724/38066653-33943ab2-3333-11e8-8e89-1857704dc738.png)

**Comment by sxcooler** [comment]
Hey guys,
I've got the same issue too, all Maps cannot be shown in mobx-devtools, no matter observable or not.
![image](https://user-images.githubusercontent.com/3192045/41152810-6074ecd8-6b47-11e8-966c-24197e8e9a6f.png)
I'm pretty sure this map is not empty.
I suppose it's some kind of issue related to mobx versions, I'm now using mobx 4.1.0, and if I remember right, mobx 3.x use Object to implement observable Map, but now in 4.x using native Map().

**Comment by fortezhuo** [comment]
Hi @sxcooler 
I had uninstalled this chrome extension. And I forgot to follow up this issue. 
And you can go with solution from https://github.com/zalmoxisus/mobx-remotedev

For this issue, I will remain open till it solved

**Comment by sxcooler** [comment]
@hedikasmanto Thanks a lot.
